[package]
name = "hologram-catalyst-repo"
version = "1.1.3"
description = "hologram: enable Catalyst repository"
requires = [
    "holo>=0.10",
    "pacman",
]

# import the GPG key for the catalyst repository
setupScript = "pacman-key -r 653C3094"

# add catalyst repo to pacman.conf (before all other repos, as instructed by the Arch wiki)
# (also add the xorg-server-1.17 repo as Catalyst 15.9 does not support xorg-server-1.18 yet)
[[file]]
path    = "/usr/share/holo/files/20-catalyst/etc/pacman.conf.holoscript"
mode    = "0755"
content = """
    #!/bin/sh
    echo '[xorg117]'
    echo 'Server = http://catalyst.wirephire.com/repo/xorg117/$arch'
    echo
    echo '[catalyst]'
    echo 'Server = http://catalyst.wirephire.com/repo/catalyst/$arch'
    echo
    cat
"""
