[package]
name        = "hologram-dev-tools"
version     = "1.1.1"
description = "hologram: compilers and development tools"
definitionFile = "/usr/share/holo/users-groups/50-arduino.toml"

requires = [
    "apitrace",
    "arch-install-scripts",
    "arduino",
    "automoc4",
    "cmake",
    "cloc",
    "cpanminus",
    "doxygen",
    "gdb",
    "go",
    "go-tools",
    "holo-build",
    "perl-ipc-system-simple", # required for build_package.pl in this repo
    "perl-term-readkey",      # required for "interactive.singlekey" config of Git
    "pkgbuild-introspection",
    "rust",
    "sloccount",
    "valgrind",
]

[[user]]
name   = "stefan"
groups = [ "uucp", "lock" ]
