[package]
name        = "hologram-remount-efivarfs"
version     = "1.0"
description = "hologram: remount efivarfs readonly"

# This is not in hologram-base since it only applies to UEFI systems.

[[file]]
path    = "/usr/share/holo/files/50-remount-efivarfs/etc/fstab.holoscript"
mode    = "0755"
content = """
    #!/bin/sh
    cat
    # https://github.com/systemd/systemd/issues/2402
    echo 'efivarfs /sys/firmware/efi/efivars efivarfs ro,nosuid,nodev,noexec,noatime 0 0'
"""
