[package]
name        = "holodeck-damogran"
version     = "20160131.1"
description = "holodeck: services on Damogran"

requires = [
    "hologram-base",
    "hologram-multimedia-base",
    "hologram-damogran-dyndns",
    "hologram-damogran-audio",
    "hologram-remount-efivarfs",
    # install a vim without GUI components
    "vim-minimal",
    # boot loader (no intel-ucode since Damogran has an AMD CPU and chipset)
    "gummiboot",
    # network setup (local DHCP, local DNS, wireless AP, NAT from internal networks to external internet)
    "dnsmasq",
    "hostapd",
    "iptables",
    # public services
    "nginx",
    "todolist",
    "letsencrypt",
    # intranet services
    "jre7-openjdk-headless", # for Minecraft
]

# for letsencrypt
definitionFile = "/usr/share/holo/users-groups/50-damogran.toml"

# setup script is required because mkinitcpio.conf is being modified by this package
setupScript = "mkinitcpio -p linux"

# TODO: smartd to monitor RAID
# TODO: setup for Minecraft server

################################################################################
# identity

[[file]]
path    = "/etc/hostname"
content = "damogran"

[[file]]
path    = "/etc/profile.d/prettyprompt.sh"
content = """
export PRETTYPROMPT_COMMONUSER=stefan
export PRETTYPROMPT_HOSTCOLOR='0;35'
"""

################################################################################
# boot loader (systemd-boot)

[[file]]
path    = "/boot/loader/loader.conf"
content = """
    default arch
    timeout 1
"""

[[file]]
path    = "/boot/loader/entries/arch.conf"
content = """
    title     Arch Linux
    linux     /vmlinuz-linux
    initrd    /initramfs-linux.img
    options   root=PARTUUID=${DAMOGRAN_ROOT_PARTUUID} rw
"""
[[symlink]]
path   = "/usr/share/holo/files/50-damogran-vars/boot/loader/entries/arch.conf.holoscript"
target = "/my/variables"

[[file]]
path    = "/usr/share/holo/files/50-damogran/etc/mkinitcpio.conf.holoscript"
mode    = "0755"
content = """
    #!/bin/sh
    sed 's/^MODULES="/MODULES="vfat /'
"""

################################################################################
# network setup: systemd-{networkd,resolved} to configure interfaces and upstream DNS

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service"
target = "/usr/lib/systemd/system/systemd-resolved.service"

[[file]]
path    = "/etc/systemd/network/lan.network"
content = """
    [Match]
    Name=${DAMOGRAN_IFACE_LAN}

    [Network]
    Description=Internal LAN
    Address=10.0.0.1/24
    IPForward=ipv4
"""
[[symlink]]
path   = "/usr/share/holo/files/50-damogran-vars/etc/systemd/network/lan.network.holoscript"
target = "/my/variables"

[[file]]
path    = "/etc/systemd/network/wlan.network"
content = """
    [Match]
    Name=${DAMOGRAN_IFACE_WLAN}

    [Network]
    Description=Internal Wireless LAN
    Address=10.0.1.1/24
    IPForward=ipv4
"""
[[symlink]]
path   = "/usr/share/holo/files/50-damogran-vars/etc/systemd/network/wlan.network.holoscript"
target = "/my/variables"

[[file]]
path    = "/etc/systemd/network/wan.network"
content = """
    [Match]
    Name=${DAMOGRAN_IFACE_WAN}

    [Network]
    Description=External Network (Internet)
    DHCP=ipv4
"""
[[symlink]]
path   = "/usr/share/holo/files/50-damogran-vars/etc/systemd/network/wan.network.holoscript"
target = "/my/variables"

################################################################################
# network setup: an iptables ruleset acts as firewall

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/iptables.service"
target = "/usr/lib/systemd/system/iptables.service"

[[file]]
path = "/etc/sysctl.d/90-firewall.conf"
content = """
    # filter spoofing of local source addresses from internet locations
    net.ipv4.conf.all.rp_filter = 1
    # enable IPv4 forwarding (NAT)
    net.ipv4.ip_forward = 1
    net.ipv4.conf.all.forwarding = 1
    net.ipv4.conf.default.forwarding = 1
    net.ipv4.conf.${DAMOGRAN_IFACE_LAN}.forwarding = 1
    net.ipv4.conf.${DAMOGRAN_IFACE_WLAN}.forwarding = 1
    net.ipv4.conf.${DAMOGRAN_IFACE_WAN}.forwarding = 1

    # disable IPv6 for internet-facing interfaces
    net.ipv6.conf.${DAMOGRAN_IFACE_WAN}.disable_ipv6 = 1
"""
[[symlink]]
path   = "/usr/share/holo/files/50-damogran-vars/etc/sysctl.d/90-firewall.conf.holoscript"
target = "/my/variables"

[[file]]
path = "/etc/iptables/iptables.rules"
content = """
    *filter

    # standard chains
    :INPUT DROP [0:0]
    :FORWARD DROP [0:0]
    :OUTPUT ACCEPT [0:0]
    # chains for accepting incoming connections
    :TCP - [0:0]
    :UDP - [0:0]



    # accept traffic on established connections
    -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    # accept all local traffic
    -A INPUT -i lo -j ACCEPT
    # drop all invalid traffic (esp. to avoid attacks from the internet)
    -A INPUT -m conntrack --ctstate INVALID -j DROP
    # accept pings from everywhere
    -A INPUT -p icmp -m icmp --icmp-type 8 -m conntrack --ctstate NEW -j ACCEPT
    # attach chains for checking incoming connections
    -A INPUT -p udp -m conntrack --ctstate NEW -j UDP
    -A INPUT -p tcp -m tcp --syn -m conntrack --ctstate NEW -j TCP
    # reject unwanted connections
    -A INPUT -p tcp -j REJECT --reject-with tcp-reset
    -A INPUT -p udp -j REJECT --reject-with icmp-port-unreachable
    -A INPUT -j REJECT --reject-with icmp-proto-unreachable

    # allow public SSH
    -A TCP -p tcp -m tcp --dport 22 -j ACCEPT
    # allow public HTTP(S)
    -A TCP -p tcp -m tcp --dport 80 -j ACCEPT
    -A TCP -p tcp -m tcp --dport 443 -j ACCEPT
    # allow intranet PulseAudio
    -A TCP -i ${DAMOGRAN_IFACE_WLAN} -p tcp -m tcp --dport 4713 -j ACCEPT
    -A TCP -i ${DAMOGRAN_IFACE_LAN} -p tcp -m tcp --dport 4713 -j ACCEPT
    # allow intranet MPD
    -A TCP -i ${DAMOGRAN_IFACE_WLAN} -p tcp -m tcp --dport 6600 -j ACCEPT
    -A TCP -i ${DAMOGRAN_IFACE_LAN} -p tcp -m tcp --dport 6600 -j ACCEPT
    # allow public Minecraft
    -A TCP -p tcp -m tcp --dport 25565 -j ACCEPT

    # allow intranet DNS
    -A UDP -i ${DAMOGRAN_IFACE_WLAN} -p udp -m udp --dport 53 -j ACCEPT
    -A UDP -i ${DAMOGRAN_IFACE_LAN} -p udp -m udp --dport 53 -j ACCEPT
    # allow intranet DHCP
    -A UDP -i ${DAMOGRAN_IFACE_WLAN} -p udp -m udp --sport 67:68 --dport 67:68 -j ACCEPT
    -A UDP -i ${DAMOGRAN_IFACE_LAN} -p udp -m udp --sport 67:68 --dport 67:68 -j ACCEPT
    # allow intranet MDNS (for PulseAudio)
    -A UDP -i ${DAMOGRAN_IFACE_WLAN} -p udp -m udp --dport 5353 -j ACCEPT
    -A UDP -i ${DAMOGRAN_IFACE_LAN} -p udp -m udp --dport 5353 -j ACCEPT



    # accept traffic on established connections
    -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
    # accept forwarding connections from intranet to public
    -A FORWARD -i ${DAMOGRAN_IFACE_WLAN} -j ACCEPT
    -A FORWARD -i ${DAMOGRAN_IFACE_LAN} -j ACCEPT
    # reject unwanted connections
    -A FORWARD -j REJECT --reject-with icmp-host-unreachable

    COMMIT
    *nat

    # standard chains for NAT
    :PREROUTING ACCEPT [0:0]
    :INPUT ACCEPT [0:0]
    :OUTPUT ACCEPT [0:0]
    :POSTROUTING ACCEPT [0:0]

    # establish forwarding connections from intranet (IP range) to public (${DAMOGRAN_IFACE_WAN})
    -A POSTROUTING -s 10.0.0.0/24 -o ${DAMOGRAN_IFACE_WAN} -j MASQUERADE
    -A POSTROUTING -s 10.0.1.0/24 -o ${DAMOGRAN_IFACE_WAN} -j MASQUERADE

    COMMIT
"""
[[symlink]]
path   = "/usr/share/holo/files/50-damogran-vars/etc/iptables/iptables.rules.holoscript"
target = "/my/variables"

################################################################################
# network setup: hostapd to provide the WiFi access point

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/hostapd.service"
target = "/usr/lib/systemd/system/hostapd.service"

[[file]]
path    = "/etc/hostapd/hostapd.conf"
content = """
    # specify the wireless interface to operate on
    interface=${DAMOGRAN_IFACE_WLAN}
    driver=nl80211
    # enable 802.11g base functionality (n comes on top of g)
    hw_mode=g
    channel=8
    # enable 802.11n
    ieee80211n=1
    wmm_enabled=1
    # HT capabilities as detected by `iw list` and translated by the reference hostapd.conf
    ht_capab=[HT40][SHORT-GI-20][SHORT-GI-40][TX-STBC][RX-STBC1][DSSS_CCK-40]
    # enable 802.11d (advertisement of allowed channels and transmit power levels in
    # this regulatory domain)
    ieee80211d=1
    country_code=DE

    # broadcast the network ID
    ssid2="${DAMOGRAN_WLAN_SSID}"
    ignore_broadcast_ssid=0
    # enable WPA2 encryption
    auth_algs=3
    wpa=2
    wpa_passphrase=${DAMOGRAN_WLAN_PSK}
    wpa_key_mgmt=WPA-PSK
    wpa_pairwise=CCMP
    rsn_pairwise=CCMP

    # limit number of "stations" (connected clients) for good measure
    max_num_sta=20

    # log to stdout (all modules, above level 2 = informational messages)
    logger_stdout=-1
    logger_stdout_level=2
"""
[[symlink]]
path   = "/usr/share/holo/files/50-damogran-vars/etc/hostapd/hostapd.conf.holoscript"
target = "/my/variables"

################################################################################
# network setup: dnsmasq to provide DHCP and DNS in the internal networks

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/dnsmasq.service"
target = "/usr/lib/systemd/system/dnsmasq.service"

[[file]]
path    = "/etc/systemd/system/dnsmasq.service.d/reorder.conf"
content = """
    [Unit]
    After=systemd-resolved.service
    Requires=systemd-resolved.service
"""

[[file]]
path    = "/usr/share/holo/files/50-damogran/etc/dnsmasq.conf"
content = """
    # bind DHCP and DNS servers to all interfaces except external internet
    bind-interfaces
    except-interface=${DAMOGRAN_IFACE_WAN}

    # allocate IPv4 ranges for DHCP
    dhcp-range=10.0.0.100,10.0.0.199,12h
    dhcp-range=10.0.1.100,10.0.1.199,12h
    # assign a static IP address to Krikkit
    dhcp-host=${KRIKKIT_MACADDR_LAN},10.0.0.3

    # obtain upstream DNS from systemd-resolved
    resolv-file=/run/systemd/resolve/resolv.conf
    # local DNS overrides
    address=/damogran.local/10.0.0.1
    address=/arcturus.local/10.0.0.2
    address=/krikkit.local/10.0.0.3
"""
[[symlink]]
path   = "/usr/share/holo/files/50-damogran-vars/etc/dnsmasq.conf.holoscript"
target = "/my/variables"

################################################################################
# public web server

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/nginx.service"
target = "/usr/lib/systemd/system/nginx.service"

# NOTE: ssl_certificate etc. do not interpolate variables, so need to be stated per host
[[file]]
path    = "/etc/nginx/common-ssl.inc"
content = """
    listen 443 ssl;

    ssl on;
    # ssl_certificate     /etc/letsencrypt/live/$host/fullchain.pem;
    # ssl_certificate_key /etc/letsencrypt/live/$host/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    # source esp. for cipher suite selection: https://wiki.mozilla.org/Security/Server_Side_TLS
    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains"; # six months

    # Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
    # NOTE: generate this with `sudo openssl dhparam -out /etc/nginx/dhparam.pem 2048`
    ssl_dhparam /etc/nginx/dhparam.pem;

    # activate OCSP stapling (source: https://github.com/letsencrypt/letsencrypt/blob/master/letsencrypt-nginx/letsencrypt_nginx/configurator.py)
    # ssl_trusted_certificate /etc/letsencrypt/live/$host/chain.pem;
    ssl_stapling on;
    ssl_stapling_verify on;

    error_page 500 502 503 504  /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
"""

[[file]]
path    = "/usr/share/holo/files/50-damogran/etc/nginx/nginx.conf"
content = """
    # default configuration
    user http;
    worker_processes 1;
    events {
        worker_connections 1024;
    }

    http {
        include mime.types;
        default_type application/octet-stream;

        sendfile on;
        keepalive_timeout 65;

        server {
            listen      80;
            server_name repo.holocm.org;

            location / {
                return 301 https://$host$request_uri;
            }

            location /.well-known/acme-challenge/ {
                root /srv/http/repo.holocm.org;
            }
        }

        server {
            listen      80;
            server_name todolist.holocm.org;

            location / {
                return 301 https://$host$request_uri;
            }

            location /.well-known/acme-challenge/ {
                root /srv/http/todolist.holocm.org;
            }
        }

        server {
            listen      80;
            server_name static.${DAMOGRAN_HTTP_PRIVATE_DOMAIN};

            location / {
                return 301 https://$host$request_uri;
            }

            location /.well-known/acme-challenge/ {
                root /srv/http/static.${DAMOGRAN_HTTP_PRIVATE_DOMAIN};
            }
        }

        server {
            server_name repo.holocm.org;
            include     /etc/nginx/common-ssl.inc;

            ssl_certificate     /etc/letsencrypt/live/repo.holocm.org/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/repo.holocm.org/privkey.pem;
            ssl_trusted_certificate /etc/letsencrypt/live/repo.holocm.org/chain.pem;

            location / {
                root  /srv/http/repo.holocm.org;
                index index.html index.htm;
                autoindex on;
            }
        }

        server {
            server_name todolist.holocm.org;
            include     /etc/nginx/common-ssl.inc;

            ssl_certificate     /etc/letsencrypt/live/todolist.holocm.org/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/todolist.holocm.org/privkey.pem;
            ssl_trusted_certificate /etc/letsencrypt/live/todolist.holocm.org/chain.pem;

            location / {
                proxy_pass http://localhost:8113;
                proxy_set_header Authorization $http_authorization;
                proxy_pass_header Authorization;
            }
        }

        server {
            server_name static.${DAMOGRAN_HTTP_PRIVATE_DOMAIN};
            include     /etc/nginx/common-ssl.inc;

            ssl_certificate     /etc/letsencrypt/live/static.${DAMOGRAN_HTTP_PRIVATE_DOMAIN}/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/static.${DAMOGRAN_HTTP_PRIVATE_DOMAIN}/privkey.pem;
            ssl_trusted_certificate /etc/letsencrypt/live/static.${DAMOGRAN_HTTP_PRIVATE_DOMAIN}/chain.pem;

            location / {
                root  /srv/http/static.${DAMOGRAN_HTTP_PRIVATE_DOMAIN};
                index index.html index.htm;
            }
        }

    }
"""
[[symlink]]
path   = "/usr/share/holo/files/50-damogran-vars/etc/nginx/nginx.conf.holoscript"
target = "/my/variables"

################################################################################
# public web server: todolist app

[[group]]
name   = "todolist"
system = true

[[user]]
name   = "todolist"
group  = "todolist"
system = true

[[directory]]
path  = "/var/lib/todolist"
owner = "todolist"
group = "todolist"

[[file]]
path    = "/usr/lib/systemd/system/todolist.service"
content = """
    [Unit]
    Description=Minimalistic web-based todolist app

    [Service]
    ExecStart=/usr/bin/todolist -port 8113
    WorkingDirectory=/var/lib/todolist
    User=todolist

    [Install]
    WantedBy=multi-user.target
"""

[[symlink]]
path   = "/etc/systemd/system/multi-user.target.wants/todolist.service"
target = "/usr/lib/systemd/system/todolist.service"

################################################################################
# public web server: letsencrypt integration

[[group]]
name   = "letsencrypt"
system = true

[[user]]
name   = "letsencrypt"
group  = "letsencrypt"
system = true
home   = "/var/lib/letsencrypt"

[[user]]
name   = "http"
groups = ["letsencrypt"]

# fix UID/GID on directories provided by letsencrypt package
[[directory]]
path  = "/etc/letsencrypt"
owner = "letsencrypt"
group = "letsencrypt"
[[directory]]
path  = "/var/lib/letsencrypt"
owner = "letsencrypt"
group = "letsencrypt"
[[directory]]
path  = "/var/log/letsencrypt"
mode  = "0700"
owner = "letsencrypt"
group = "letsencrypt"

# these directories need to be writable by the letsencrypt user for the web challenges
[[directory]]
path  = "/srv/http/repo.holocm.org/.well-known/acme-challenge"
mode  = "0770"
owner = "letsencrypt"
group = "letsencrypt"
[[directory]]
path  = "/srv/http/todolist.holocm.org/.well-known/acme-challenge"
mode  = "0770"
owner = "letsencrypt"
group = "letsencrypt"
[[directory]]
path  = "/srv/http/static.private/.well-known/acme-challenge"
mode  = "0770"
owner = "letsencrypt"
group = "letsencrypt"

# TODO: automate the initial `letsencrypt certonly --webroot -w /srv/http/static.private -d static.${DAMOGRAN_HTTP_PRIVATE_DOMAIN}` -w /srv/http/repo.holocm.org -d repo.holocm.org -w /srv/http/todolist.holocm.org -d todolist.holocm.org

# run letsencrypt-renewer regularly
[[file]]
path    = "/usr/lib/systemd/system/letsencrypt-renewer.service"
content = """
    [Unit]
    Description=Check and renew TLS certificates
    After=network-online.target gandi-dyndns.service
    Wants=network-online.target gandi-dyndns.service

    [Service]
    Type=oneshot
    ExecStart=/usr/bin/letsencrypt-renewer
    User=letsencrypt
"""

[[file]]
path    = "/usr/lib/systemd/system/letsencrypt-renewer.timer"
content = """
    [Unit]
    Description=Check and renew TLS certificates once a day
    After=network-online.target
    Wants=network-online.target

    [Timer]
    OnBootSec=1h
    OnUnitActiveSec=1d

    [Install]
    WantedBy=timers.target
"""

[[symlink]]
path   = "/etc/systemd/system/timers.target.wants/letsencrypt-renewer.timer"
target = "/usr/lib/systemd/system/letsencrypt-renewer.timer"

# take an automatic backup of /etc/letsencrypt every three days
[[file]]
path    = "/usr/lib/letsencrypt-backup.sh"
mode    = "0755"
content = """
    #!/bin/sh
    cd /
    mkdir -p /raid/data/backup-etc-letsencrypt
    chmod 0700 /raid/data/backup-etc-letsencrypt
    chown root:root /raid/data/backup-etc-letsencrypt
    tar cJf /raid/data/backup-etc-letsencrypt/$(date +%F).tar.xz /etc/letsencrypt
"""

[[file]]
path    = "/usr/lib/systemd/system/letsencrypt-backup.service"
content = """
    [Unit]
    Description=Backup /etc/letsencrypt

    [Service]
    Type=oneshot
    ExecStart=/usr/lib/letsencrypt-backup.sh
"""

[[file]]
path    = "/usr/lib/systemd/system/letsencrypt-backup.timer"
content = """
    [Unit]
    Description=Backup /etc/letsencrypt once a day

    [Timer]
    OnBootSec=3h
    OnUnitActiveSec=3d

    [Install]
    WantedBy=timers.target
"""

[[symlink]]
path   = "/etc/systemd/system/timers.target.wants/letsencrypt-backup.timer"
target = "/usr/lib/systemd/system/letsencrypt-backup.timer"
