[package]
name        = "holodeck-krikkit"
version     = "20151102-5"
description = "Holodeck: services on Krikkit"
requires    = [
    "holo",
    "hologram-kde-desktop",
    "hologram-dev-tools",
    "hologram-games",
    "hologram-dtp",
    # hardware support
    "intel-ucode",
    "xf86-video-intel",
    "xf86-input-synaptics",
    "libva-intel-driver",
    # applications
    "mpd",
    "openvpn",
    "pkgfile",
    "plasma-nm",
    "skype",
    "virtualbox",
]
# TODO: holo-build should set this up itself
setupScript = "holo apply"
cleanupScript = "holo apply"

[[file]]
path    = "/etc/hostname"
content = "krikkit"

# TODO: offer native entity handling in holo-build
# enable VirtualBox for my user account
[[file]]
path    = "/usr/share/holo/50-krikkit.toml"
content = """
[[user]]
name = "stefan"
groups = ["vboxusers"]
"""

# /etc/pulse/default.pa: disable corking which would mute MPD while Mumble or Skype are running
[[file]]
path = "/usr/share/holo/repo/50-krikkit/etc/pulse/default.pa.holoscript"
mode = "0755"
content = """
#!/bin/sh
sed '/load-module module-role-cork/d'
"""

[[file]]
path = "/etc/systemd/logind.conf.d/no-magic-suspend.conf"
content = """
[Login]
HandlePowerKey=ignore
HandleLidSwitch=ignore
"""
